In [1]:
!pip -q install transformers==4.17
!pip -q install optuna
!pip install datasets
!pip install torchinfo

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/67.9 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 27.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 21.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 3.3.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 4.17.0 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.4/383.4 kB 17.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.6/233.6 kB 11.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 17.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 13.7

In [2]:
from transformers import Trainer, TrainingArguments, AutoModel, AutoTokenizer, AutoModelForSequenceClassification
from datasets import load_dataset
import torch
import pandas as pd
import nltk
import re
import ast
import numpy as np
from torch.utils.data import Dataset
from sklearn.metrics import precision_score, recall_score, f1_score, precision_recall_fscore_support, accuracy_score
from sklearn.model_selection import train_test_split
import torch.nn as nn
import optuna
import time
from torchinfo import summary
from tabulate import tabulate

**Dataset Utilization provided by NLBSE**

In [3]:
splits = {'python_train': 'data/python_train-00000-of-00001.parquet', 'python_test': 'data/python_test-00000-of-00001.parquet'}
train_df = pd.read_parquet("hf://datasets/NLBSE/nlbse25-code-comment-classification/" + splits["python_train"])
test_df = pd.read_parquet("hf://datasets/NLBSE/nlbse25-code-comment-classification/" + splits["python_test"])

display(train_df.head())
display(test_df.head())

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


index        class                                   comment_sentence  \
0      1  AccessMixin                                     functionality.   
1      8       Atomic  when it s used as a decorator, call wraps the ...   
2     10       Atomic  when it s used as a context manager, enter cre...   
3     12       Atomic  exit commits the transaction or releases the s...   
4     14       Atomic  it s possible to disable the creation of savep...   

   partition                                              combo  \
0          0                       functionality. | AccessMixin   
1          0  when it s used as a decorator, call wraps the ...   
2          0  when it s used as a context manager, enter cre...   
3          0  exit commits the transaction or releases the s...   
4          0  it s possible to disable the creation of savep...   

            labels  
0  [0, 0, 0, 0, 1]  
1  [1, 0, 0, 0, 0]  
2  [1, 0, 0, 0, 0]  
3  [1, 0, 0, 0, 0]  
4  [1, 0, 0, 0, 0]

index           class                                   comment_sentence  \
0      0     AccessMixin  abstract cbv mixin that gives access mixins th...   
1      2  AmbiguityError     more than one migration matches a name prefix.   
2      3   AppConfigStub                              stub of an appconfig.   
3      4   AppConfigStub        only provides a label and a dict of models.   
4      5         Archive  the external api class that encapsulates an ar...   

   partition                                              combo  \
0          1  abstract cbv mixin that gives access mixins th...   
1          1  more than one migration matches a name prefix....   
2          1              stub of an appconfig. | AppConfigStub   
3          1  only provides a label and a dict of models. | ...   
4          1  the external api class that encapsulates an ar...   

            labels  
0  [0, 0, 0, 0, 1]  
1  [0, 0, 0, 0, 1]  
2  [0, 0, 0, 0, 1]  
3  [0, 1, 0, 0, 0]  
4  [0, 0, 1, 0, 1]

In [4]:
def remove_punctuation_except_pipe(text):
    return re.sub(r"[^\w\s\|]", "", text)

# Apply the function to the 'combo' column
train_df['combo'] = train_df['combo'].apply(remove_punctuation_except_pipe)
test_df['combo'] = test_df['combo'].apply(remove_punctuation_except_pipe)

# Convert data to lowercase
train_str_df = train_df[["class", "comment_sentence", "combo"]].applymap(
    lambda x: x.lower() if isinstance(x, str) else str(x)
)
test_str_df = test_df[["class", "comment_sentence", "combo"]].applymap(
    lambda x: x.lower() if isinstance(x, str) else str(x)
)

train_df[["class", "comment_sentence", "combo"]] = train_str_df[["class", "comment_sentence", "combo"]]
test_df[["class", "comment_sentence", "combo"]] = test_str_df[["class", "comment_sentence", "combo"]]

display(train_df.head())
display(test_df.head())

<ipython-input-4-df4392ae2e99>:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  train_str_df = train_df[["class", "comment_sentence", "combo"]].applymap(
<ipython-input-4-df4392ae2e99>:12: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  test_str_df = test_df[["class", "comment_sentence", "combo"]].applymap(


index        class                                   comment_sentence  \
0      1  accessmixin                                     functionality.   
1      8       atomic  when it s used as a decorator, call wraps the ...   
2     10       atomic  when it s used as a context manager, enter cre...   
3     12       atomic  exit commits the transaction or releases the s...   
4     14       atomic  it s possible to disable the creation of savep...   

   partition                                              combo  \
0          0                        functionality | accessmixin   
1          0  when it s used as a decorator call wraps the e...   
2          0  when it s used as a context manager enter crea...   
3          0  exit commits the transaction or releases the s...   
4          0  it s possible to disable the creation of savep...   

            labels  
0  [0, 0, 0, 0, 1]  
1  [1, 0, 0, 0, 0]  
2  [1, 0, 0, 0, 0]  
3  [1, 0, 0, 0, 0]  
4  [1, 0, 0, 0, 0]

index           class                                   comment_sentence  \
0      0     accessmixin  abstract cbv mixin that gives access mixins th...   
1      2  ambiguityerror     more than one migration matches a name prefix.   
2      3   appconfigstub                              stub of an appconfig.   
3      4   appconfigstub        only provides a label and a dict of models.   
4      5         archive  the external api class that encapsulates an ar...   

   partition                                              combo  \
0          1  abstract cbv mixin that gives access mixins th...   
1          1  more than one migration matches a name prefix ...   
2          1               stub of an appconfig | appconfigstub   
3          1  only provides a label and a dict of models | a...   
4          1  the external api class that encapsulates an ar...   

            labels  
0  [0, 0, 0, 0, 1]  
1  [0, 0, 0, 0, 1]  
2  [0, 0, 0, 0, 1]  
3  [0, 1, 0, 0, 0]  
4  [0, 0, 1, 0, 1]

In [5]:
X = list(train_df['combo'])
y = list(train_df['labels'])

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

In [6]:
tokenizer = AutoTokenizer.from_pretrained('microsoft/codebert-base')
model = AutoModelForSequenceClassification.from_pretrained('microsoft/codebert-base', num_labels=5)

Downloading:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/498 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/150 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Downloading:   0%|          | 0.00/476M [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/transformers/modeling_utils.py:1439: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(resolved_archive_file, map

In [7]:
class TextClassificationDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, device="cpu"):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.device = device

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, index):
        text = self.texts[index]
        label = self.labels[index]

        encoded_text = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=256,
            padding='max_length',
            truncation=True,
            return_token_type_ids=False,
            return_attention_mask=True,
            return_tensors='pt',
        )

        input_ids = encoded_text['input_ids'].squeeze().to(self.device)
        attention_mask = encoded_text['attention_mask'].squeeze().to(self.device)
        label = torch.tensor(label, dtype=torch.float).to(self.device)

        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'labels': label
        }

train_dataset = TextClassificationDataset(X_train, y_train, tokenizer)
eval_dataset = TextClassificationDataset(X_val, y_val, tokenizer)

In [8]:
class OneHotTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False):
        labels = inputs.get("labels")
        # Remove 'labels' from inputs before passing to model
        model_inputs = {k: v for k, v in inputs.items() if k != "labels"}
        outputs = model(**model_inputs)  # Pass only the required inputs to the model
        logits = outputs.get("logits")

        if logits is None:
            # Handle the case where logits are missing, e.g., raise an exception or return a default loss
            raise ValueError("Logits are missing from the model output.")  # Or return a default loss

        # Use BCEWithLogitsLoss for multi-label classification
        loss_fct = nn.BCEWithLogitsLoss()
        loss = loss_fct(logits, labels.float())

        return (loss, outputs) if return_outputs else loss

In [9]:
def compute_metrics(pred):
    logits = pred.predictions
    preds = (logits > 0).astype(int)

    labels = pred.label_ids

    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    accuracy = (preds == labels).mean()

    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1
    }


In [10]:
# def objective(trial):
#     learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
#     batch_size = trial.suggest_categorical("batch_size", [4, 8, 16])
#     num_train_epochs = trial.suggest_int("num_train_epochs", 3, 10)
#     weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)

#     training_args = TrainingArguments(
#         output_dir="./results",
#         num_train_epochs=num_train_epochs,
#         per_device_train_batch_size=batch_size,
#         per_device_eval_batch_size=batch_size * 2,
#         warmup_steps=10,
#         weight_decay=weight_decay,
#         evaluation_strategy="epoch",
#         learning_rate=learning_rate,
#         gradient_accumulation_steps=2,
#         report_to="none",
#     )

#     trainer = OneHotTrainer(
#         model=model,
#         args=training_args,
#         train_dataset=train_dataset,
#         eval_dataset=eval_dataset,
#         compute_metrics=compute_metrics,
#     )

#     trainer.train()
#     eval_results = trainer.evaluate()

#     return eval_results["eval_f1"]

In [11]:
# study = optuna.create_study(direction="maximize")
# study.optimize(objective, n_trials=10)

# print("Best trial:")
# print(study.best_trial)

In [ ]:
training_args = TrainingArguments(
    output_dir="./best_results",
    num_train_epochs=12,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4 * 2,
    learning_rate=2e-05,
    weight_decay=0.023,
    warmup_steps=10,
    evaluation_strategy="epoch",
    gradient_accumulation_steps=2,
    report_to="none",
)

trainer = OneHotTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics,
)
trainer.train()

/usr/local/lib/python3.11/dist-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 1507
  Num Epochs = 12
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 2
  Total optimization steps = 2256


***** Running Evaluation *****
  Num examples = 377
  Batch size = 8
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 377
  Batch size = 8
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
Saving model checkpoint to ./best_results/checkpoint-500
Configuration saved in ./best_results/checkpoint-500/config.json
Model weights saved in ./best_results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Nu

TrainOutput(global_step=2256, training_loss=0.17300891326674334, metrics={'train_runtime': 983.5261, 'train_samples_per_second': 18.387, 'train_steps_per_second': 2.294, 'total_flos': 2378719566945792.0, 'train_loss': 0.17300891326674334, 'epoch': 12.0})

In [ ]:
eval_results = trainer.evaluate()

***** Running Evaluation *****
  Num examples = 377
  Batch size = 8


### Model Saving

In [ ]:
!mkdir 'best_model_codebert-base_python'
!mkdir 'best_model_codebert-base_python_tokenizer'

# Save model and tokenizer
trainer.save_model('./best_model_codebert-base_python')
tokenizer.save_pretrained('./best_model_codebert-base_python_tokenizer')

# Load model and tokenizer
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained('./best_model_codebert-base_python')
tokenizer = AutoTokenizer.from_pretrained('./best_model_codebert-base_python_tokenizer')

Saving model checkpoint to ./best_model_codebert-base_python
Configuration saved in ./best_model_codebert-base_python/config.json
Model weights saved in ./best_model_codebert-base_python/pytorch_model.bin
tokenizer config file saved in ./best_model_codebert-base_python_tokenizer/tokenizer_config.json
Special tokens file saved in ./best_model_codebert-base_python_tokenizer/special_tokens_map.json
loading configuration file ./best_model_codebert-base_python/config.json
Model config RobertaConfig {
  "_name_or_path": "./best_model_codebert-base_python",
  "architectures": [
    "RobertaForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id":

### Model Testing

In [ ]:
X_test = list(test_df['combo'])
y_test = list(test_df['labels'])

In [ ]:
df_test = pd.DataFrame({"combo":X_test,"labels":y_test})
test_text = df_test.combo.values
test_label = df_test.labels.values

print(test_label)

[array([0, 0, 0, 0, 1]) array([0, 0, 0, 0, 1]) array([0, 0, 0, 0, 1])
 array([0, 1, 0, 0, 0]) array([0, 0, 1, 0, 1]) array([0, 0, 0, 0, 1])
 array([0, 0, 0, 0, 1]) array([1, 0, 0, 1, 0]) array([1, 0, 0, 0, 0])
 array([1, 0, 0, 0, 0]) array([1, 0, 0, 0, 0]) array([1, 0, 0, 0, 0])
 array([1, 0, 0, 0, 0]) array([0, 0, 0, 0, 1]) array([0, 0, 0, 1, 0])
 array([0, 0, 0, 1, 0]) array([0, 0, 0, 1, 0]) array([0, 0, 0, 1, 0])
 array([0, 0, 0, 0, 1]) array([0, 0, 0, 1, 0]) array([1, 0, 0, 0, 0])
 array([1, 0, 0, 0, 0]) array([0, 0, 1, 0, 0]) array([0, 0, 0, 0, 1])
 array([1, 0, 0, 0, 0]) array([1, 0, 0, 0, 0]) array([0, 1, 0, 0, 0])
 array([0, 1, 0, 0, 0]) array([0, 1, 0, 0, 0]) array([0, 1, 0, 0, 0])
 array([0, 1, 0, 0, 0]) array([0, 1, 0, 0, 0]) array([0, 0, 0, 1, 0])
 array([0, 0, 0, 1, 0]) array([0, 0, 0, 1, 0]) array([0, 0, 0, 1, 0])
 array([0, 0, 1, 0, 0]) array([0, 0, 0, 0, 1]) array([0, 0, 0, 0, 1])
 array([0, 0, 0, 0, 1]) array([0, 0, 0, 0, 1]) array([0, 0, 1, 0, 0])
 array([0, 0, 0, 0, 

In [ ]:
test_dataset = TextClassificationDataset(test_text, test_label, tokenizer)

# Measure inference time
start_time = time.time()

# Predict on the test dataset
predictions = trainer.predict(test_dataset)

# Calculate elapsed time
end_time = time.time()
inference_time = end_time - start_time

# Compute metrics using the `compute_metrics` function
metrics = compute_metrics(predictions)

# Display metrics and inference time
print("Evaluation Metrics:", metrics)
print(f"Inference Time: {inference_time:.2f} seconds")

***** Running Prediction *****
  Num examples = 406
  Batch size = 8


Evaluation Metrics: {'accuracy': 0.8689655172413793, 'precision': 0.7022704142240778, 'recall': 0.6857798165137615, 'f1': 0.691509916323865}
Inference Time: 5.87 seconds


In [ ]:
!zip -r best_model_codebert-base_python.zip './best_model_codebert-base_python'
!zip -r best_model_codebert-base_python_tokenizer.zip './best_model_codebert-base_python_tokenizer'

  adding: best_model_codebert-base_python/ (stored 0%)
  adding: best_model_codebert-base_python/pytorch_model.bin (deflated 7%)
  adding: best_model_codebert-base_python/config.json (deflated 53%)
  adding: best_model_codebert-base_python/training_args.bin (deflated 51%)
  adding: best_model_codebert-base_python_tokenizer/ (stored 0%)
  adding: best_model_codebert-base_python_tokenizer/special_tokens_map.json (deflated 51%)
  adding: best_model_codebert-base_python_tokenizer/tokenizer_config.json (deflated 73%)
  adding: best_model_codebert-base_python_tokenizer/vocab.json (deflated 59%)
  adding: best_model_codebert-base_python_tokenizer/tokenizer.json (deflated 82%)
  adding: best_model_codebert-base_python_tokenizer/merges.txt (deflated 53%)


In [ ]:
# Transferring the model to Google Drive
from google.colab import drive
drive.mount('/content/drive')

!cp best_model_codebert-base_python.zip "/content/drive/MyDrive/FYP/Revised/Models/codebert-base_Python/"
!cp best_model_codebert-base_python_tokenizer.zip "/content/drive/MyDrive/FYP/Revised/Models/codebert-base_Python_Tokenizer/"

ValueError: mount failed

### Load and Test Model

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Replace 'path/to/checkpoint-folder' with the actual path to your checkpoint folder.
model_folder = '/content/drive/MyDrive/FYP/Revised/Models/codebert-base_Python/'
tokenizer_folder = '/content/drive/MyDrive/FYP/Revised/Models/codebert-base_Python_Tokenizer/'

!unzip '/content/drive/MyDrive/FYP/Revised/Models/codebert-base_Python/best_model_codebert-base_python.zip' -d './'
!unzip '/content/drive/MyDrive/FYP/Revised/Models/codebert-base_Python_Tokenizer/best_model_codebert-base_python_tokenizer.zip' -d './'

In [ ]:
best_model_codebert_base_python = 'best_model_codebert-base_python'
best_model_codebert_base_python_tokenizer = 'best_model_codebert-base_python_tokenizer'

In [ ]:
# Load the model and tokenizer from the checkpoint
model = AutoModelForSequenceClassification.from_pretrained(best_model_codebert_base_python)
tokenizer = AutoTokenizer.from_pretrained(best_model_codebert_base_python_tokenizer)

In [ ]:
text = "for detecting automatically generated fields."
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
output

In [ ]:
logits = output.logits

# Apply sigmoid to convert logits to probabilities
probabilities = torch.sigmoid(logits)

# Define a threshold to determine if a class is positive
threshold = 0.5
predicted_indices = (probabilities > threshold).nonzero(as_tuple=True)[1]

# Convert indices to a list for output
predicted_classes = (predicted_indices + 1).tolist()

# Format the output to display classes
if len(predicted_classes) > 0:
    predicted_classes_str = ", ".join(map(str, predicted_classes))
    print(f"Predicted class/es: {predicted_classes_str}")
else:
    print("No positive classes predicted.")