In [1]:
!pip install transformers==4.17
!pip install optuna

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/67.9 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 62.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 44.0 MB/s eta 0:00:00
  Attempting uninstall: transformers
    Found existing installation: transformers 4.46.2
    Uninstalling transformers-4.46.2:
      Successfully uninstalled transformers-4.46.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 3.2.1 requires transformers<5.0.0,>=4.41.0, but you have transformers 4.17.0 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 364.4/364.4 kB 19.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.5/233.5 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 4.9 MB/s eta 0:00:00


In [2]:
from transformers import Trainer, TrainingArguments, DistilBertTokenizer, DistilBertForSequenceClassification
import torch
import pandas as pd
import nltk
import re
import ast
import numpy as np
from torch.utils.data import Dataset
from sklearn.metrics import precision_score, recall_score, f1_score, precision_recall_fscore_support, accuracy_score
from sklearn.model_selection import train_test_split
import torch.nn as nn
import optuna
import time

In [3]:
splits = {'pharo_train': 'data/pharo_train-00000-of-00001.parquet', 'pharo_test': 'data/pharo_test-00000-of-00001.parquet'}
train_df = pd.read_parquet("hf://datasets/NLBSE/nlbse25-code-comment-classification/" + splits["pharo_train"])
test_df = pd.read_parquet("hf://datasets/NLBSE/nlbse25-code-comment-classification/" + splits["pharo_test"])

display(train_df.head())
display(test_df.head())
display(train_df.shape)
display(test_df.shape)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


index                      class  \
0      0  BlAnchorRelativeToElement   
1      2     BlArrowheadSimpleArrow   
2      3     BlArrowheadSimpleArrow   
3      4     BlArrowheadSimpleArrow   
4      8        BlArrowheadTriangle   

                                    comment_sentence  partition  \
0  relative anchor takes an arbitrary element as ...          0   
1                i am a simple arrow like arrowhead.          0   
2  both my size and arrow length depend on the cu...          0   
3  it is possible hovewer to customize a length f...          0   
4                      i am a triangular arrow head.          0   

                                               combo                 labels  
0  relative anchor takes an arbitrary element as ...  [0, 0, 1, 0, 0, 0, 0]  
1  i am a simple arrow like arrowhead. | BlArrowh...  [0, 0, 0, 0, 1, 0, 0]  
2  both my size and arrow length depend on the cu...  [0, 0, 0, 0, 1, 0, 0]  
3  it is possible hovewer to customize a length f...  [0, 0, 0, 0, 0, 1, 0]  
4  i am a triangular arrow head. | BlArrowheadTri...  [0, 0, 0, 0, 1, 0, 0]

index                   class  \
0      1     BlArrowheadExamples   
1      5  BlArrowheadSimpleArrow   
2      6  BlArrowheadSimpleArrow   
3      7  BlArrowheadSimpleArrow   
4      9     BlArrowheadTriangle   

                                    comment_sentence  partition  \
0  i contain examples of different types of blarr...          1   
1  users can also customise nose angle that tells...          1   
2  the with of the outer arrows can be specified ...          1   
3  i support both background and border paint and...          1   
4  my size depends on the width of a curve and he...          1   

                                               combo                 labels  
0  i contain examples of different types of blarr...  [0, 0, 1, 1, 0, 0, 0]  
1  users can also customise nose angle that tells...  [0, 1, 0, 0, 0, 0, 0]  
2  the with of the outer arrows can be specified ...  [0, 0, 1, 0, 0, 0, 0]  
3  i support both background and border paint and...  [0, 0, 1, 0, 0, 0, 0]  
4  my size depends on the width of a curve and he...  [0, 0, 1, 0, 0, 0, 0]

(1298, 6)

(289, 6)

In [4]:
def remove_punctuation_except_pipe(text):
    return re.sub(r"[^\w\s\|]", "", text)

# Apply the function to the 'combo' column
train_df['combo'] = train_df['combo'].apply(remove_punctuation_except_pipe)
test_df['combo'] = test_df['combo'].apply(remove_punctuation_except_pipe)

# Convert data to lowercase
train_str_df = train_df[["class", "comment_sentence", "combo"]].applymap(
    lambda x: x.lower() if isinstance(x, str) else str(x)
)
test_str_df = test_df[["class", "comment_sentence", "combo"]].applymap(
    lambda x: x.lower() if isinstance(x, str) else str(x)
)

train_df[["class", "comment_sentence", "combo"]] = train_str_df[["class", "comment_sentence", "combo"]]
test_df[["class", "comment_sentence", "combo"]] = test_str_df[["class", "comment_sentence", "combo"]]

display(train_df.head())
display(test_df.head())

<ipython-input-4-df4392ae2e99>:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  train_str_df = train_df[["class", "comment_sentence", "combo"]].applymap(
<ipython-input-4-df4392ae2e99>:12: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  test_str_df = test_df[["class", "comment_sentence", "combo"]].applymap(


index                      class  \
0      0  blanchorrelativetoelement   
1      2     blarrowheadsimplearrow   
2      3     blarrowheadsimplearrow   
3      4     blarrowheadsimplearrow   
4      8        blarrowheadtriangle   

                                    comment_sentence  partition  \
0  relative anchor takes an arbitrary element as ...          0   
1                i am a simple arrow like arrowhead.          0   
2  both my size and arrow length depend on the cu...          0   
3  it is possible hovewer to customize a length f...          0   
4                      i am a triangular arrow head.          0   

                                               combo                 labels  
0  relative anchor takes an arbitrary element as ...  [0, 0, 1, 0, 0, 0, 0]  
1  i am a simple arrow like arrowhead | blarrowhe...  [0, 0, 0, 0, 1, 0, 0]  
2  both my size and arrow length depend on the cu...  [0, 0, 0, 0, 1, 0, 0]  
3  it is possible hovewer to customize a length f...  [0, 0, 0, 0, 0, 1, 0]  
4  i am a triangular arrow head | blarrowheadtria...  [0, 0, 0, 0, 1, 0, 0]

index                   class  \
0      1     blarrowheadexamples   
1      5  blarrowheadsimplearrow   
2      6  blarrowheadsimplearrow   
3      7  blarrowheadsimplearrow   
4      9     blarrowheadtriangle   

                                    comment_sentence  partition  \
0  i contain examples of different types of blarr...          1   
1  users can also customise nose angle that tells...          1   
2  the with of the outer arrows can be specified ...          1   
3  i support both background and border paint and...          1   
4  my size depends on the width of a curve and he...          1   

                                               combo                 labels  
0  i contain examples of different types of blarr...  [0, 0, 1, 1, 0, 0, 0]  
1  users can also customise nose angle that tells...  [0, 1, 0, 0, 0, 0, 0]  
2  the with of the outer arrows can be specified ...  [0, 0, 1, 0, 0, 0, 0]  
3  i support both background and border paint and...  [0, 0, 1, 0, 0, 0, 0]  
4  my size depends on the width of a curve and he...  [0, 0, 1, 0, 0, 0, 0]

In [5]:
X = list(train_df['combo'])
y = list(train_df['labels'])

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

In [6]:
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=7)

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/483 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:1439: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(resolved_archive_file, map

In [7]:
class TextClassificationDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, device="cpu"):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.device = device

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, index):
        text = self.texts[index]
        label = self.labels[index]

        encoded_text = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=256,
            padding='max_length',
            truncation=True,
            return_token_type_ids=False,
            return_attention_mask=True,
            return_tensors='pt',
        )

        input_ids = encoded_text['input_ids'].squeeze().to(self.device)
        attention_mask = encoded_text['attention_mask'].squeeze().to(self.device)
        label = torch.tensor(label, dtype=torch.float).to(self.device)

        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'labels': label
        }

train_dataset = TextClassificationDataset(X_train, y_train, tokenizer)
eval_dataset = TextClassificationDataset(X_val, y_val, tokenizer)

In [8]:
class OneHotTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")

        # Use BCEWithLogitsLoss for multi-label classification
        loss_fct = nn.BCEWithLogitsLoss()
        loss = loss_fct(logits, labels.float())

        return (loss, outputs) if return_outputs else loss

In [9]:
def compute_metrics(pred):
    logits = pred.predictions
    preds = (logits > 0).astype(int)

    labels = pred.label_ids

    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    accuracy = (preds == labels).mean()

    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1
    }


# Optional compute_metrics function to get the accuracy, precision, recall, f1 for each of the individual labels
# without averaging them

# from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# def compute_metrics(pred):
#     # Get predictions and apply sigmoid to get probabilities
#     logits = pred.predictions
#     preds = (logits > 0).astype(int)  # Threshold at 0 to get binary predictions

#     # Get true labels
#     labels = pred.label_ids

#     # Calculate precision, recall, and f1-score for each label without averaging
#     precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average=None)
#     # Calculate accuracy per label (how many times each label is correctly predicted)
#     accuracy_per_label = (preds == labels).mean(axis=0)

#     # Prepare a dictionary to store metrics per category
#     metrics = {
#         'accuracy_per_label': accuracy_per_label,
#         'precision_per_label': precision,
#         'recall_per_label': recall,
#         'f1_per_label': f1
#     }

#     # Optionally, if you want to calculate an overall accuracy:
#     overall_accuracy = (preds == labels).all(axis=1).mean()  # This gives the fraction of samples where all labels are correctly predicted
#     metrics['overall_accuracy'] = overall_accuracy

#     return metrics

In [10]:
def objective(trial):
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
    batch_size = trial.suggest_categorical("batch_size", [4, 8, 16])
    num_train_epochs = trial.suggest_int("num_train_epochs", 3, 10)
    weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)

    training_args = TrainingArguments(
        output_dir="./results",
        num_train_epochs=num_train_epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size * 2,
        warmup_steps=10,
        weight_decay=weight_decay,
        evaluation_strategy="epoch",
        learning_rate=learning_rate,
        gradient_accumulation_steps=2,
        report_to="none",
    )

    trainer = OneHotTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        compute_metrics=compute_metrics,
    )

    trainer.train()
    eval_results = trainer.evaluate()

    return eval_results["eval_f1"]

In [11]:
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=20)

print("Best trial:")
print(study.best_trial)

[I 2024-12-01 14:16:24,287] A new study created in memory with name: no-name-ed166ca4-021f-4b97-bc85-d6904881f17d
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=Tru

***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in la

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2024-12-01 14:20:49,832] Trial 0 finished with value: 0.1560758082497213 and parameters: {'learning_rate': 1.6988743069743781e-06, 'batch_size': 8, 'num_train_epochs': 10, 'weight_decay': 0.0035024059700821735}. Best is trial 0 with value: 0.1560758082497213.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This fea

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in label

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2024-12-01 14:25:33,139] Trial 1 finished with value: 0.3020723568668774 and parameters: {'learning_rate': 1.271037659421641e-06, 'batch_size': 4, 'num_train_epochs': 10, 'weight_decay': 0.0032975072695988154}. Best is trial 1 with value: 0.3020723568668774.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feat

***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in la

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2024-12-01 14:27:37,037] Trial 2 finished with value: 0.38282816989212337 and parameters: {'learning_rate': 3.605502110138201e-06, 'batch_size': 8, 'num_train_epochs': 5, 'weight_decay': 0.00045621285103175413}. Best is trial 2 with value: 0.38282816989212337.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This fe

***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in la

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2024-12-01 14:29:34,696] Trial 3 finished with value: 0.40355272661610686 and parameters: {'learning_rate': 1.0393218576021347e-06, 'batch_size': 16, 'num_train_epochs': 5, 'weight_decay': 0.00014032164890585448}. Best is trial 3 with value: 0.40355272661610686.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This 

***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in la

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2024-12-01 14:33:24,473] Trial 4 finished with value: 0.7264040360270356 and parameters: {'learning_rate': 9.188468294207193e-06, 'batch_size': 8, 'num_train_epochs': 9, 'weight_decay': 0.00010539412952254231}. Best is trial 4 with value: 0.7264040360270356.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feat

***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
***** Running Evaluation *****
  Num examples = 260
  Batch size = 16
***** Running Evaluation *****
  Num examples = 260
  Batch size = 16


Training completed. Do not forget to share your model on huggingface.co/models =)




[I 2024-12-01 14:35:03,761] Trial 5 finished with value: 0.7868995939415069 and parameters: {'learning_rate': 2.7332338695205686e-05, 'batch_size': 8, 'num_train_epochs': 4, 'weight_decay': 0.0022032436916103195}. Best is trial 5 with value: 0.7868995939415069.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: 

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


[I 2024-12-01 14:38:20,654] Trial 6 finished with value: 0.8067980354601985 and parameters: {'learning_rate': 1.0486715718027589e-06, 'batch_size': 4, 'num_train_epochs': 7, 'weight_decay': 0.00014885888861409643}. Best is trial 6 with value: 0.8067980354601985.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning:

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


[I 2024-12-01 14:39:42,398] Trial 7 finished with value: 0.8034700470278808 and parameters: {'learning_rate': 9.592692155404668e-06, 'batch_size': 4, 'num_train_epochs': 3, 'weight_decay': 0.0012823484335803693}. Best is trial 6 with value: 0.8067980354601985.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: T

***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32


Training completed. Do not forget to share your model on huggingface.co/models =)


***** Running Evaluation *****
  Num examples = 260
  Batch size = 32


[I 2024-12-01 14:40:53,530] Trial 8 finished with value: 0.8062221526726409 and parameters: {'learning_rate': 7.595421221221269e-06, 'batch_size': 16, 'num_train_epochs': 3, 'weight_decay': 0.00023468343952974877}. Best is trial 6 with value: 0.8067980354601985.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning:

***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32


Training completed. Do not forget to share your model on huggingface.co/models =)


***** Running Evaluation *****
  Num examples = 260
  Batch size = 32


[I 2024-12-01 14:44:23,784] Trial 9 finished with value: 0.7933811348959342 and parameters: {'learning_rate': 3.341909899120127e-05, 'batch_size': 16, 'num_train_epochs': 9, 'weight_decay': 0.08064019059097263}. Best is trial 6 with value: 0.8067980354601985.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: Th

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


[I 2024-12-01 14:47:38,899] Trial 10 finished with value: 0.8101404654877471 and parameters: {'learning_rate': 2.8704044839404945e-06, 'batch_size': 4, 'num_train_epochs': 7, 'weight_decay': 0.020390434170228667}. Best is trial 10 with value: 0.8101404654877471.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning:

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


[I 2024-12-01 14:50:58,421] Trial 11 finished with value: 0.8066380801124861 and parameters: {'learning_rate': 3.122851324123773e-06, 'batch_size': 4, 'num_train_epochs': 7, 'weight_decay': 0.023605776604339452}. Best is trial 10 with value: 0.8101404654877471.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: 

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


[I 2024-12-01 14:54:15,081] Trial 12 finished with value: 0.8087666476714583 and parameters: {'learning_rate': 2.7826119542352988e-06, 'batch_size': 4, 'num_train_epochs': 7, 'weight_decay': 0.0167609044857177}. Best is trial 10 with value: 0.8101404654877471.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: T

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


[I 2024-12-01 14:57:09,471] Trial 13 finished with value: 0.8013667330464279 and parameters: {'learning_rate': 3.838281406111147e-06, 'batch_size': 4, 'num_train_epochs': 6, 'weight_decay': 0.016075573740437228}. Best is trial 10 with value: 0.8101404654877471.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: 

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-1000
Configuration saved in ./results/checkpoint-1000/config.json
Model weights saved in ./results/checkpoint-1000/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***

[I 2024-12-01 15:01:04,221] Trial 14 finished with value: 0.8087992452414245 and parameters: {'learning_rate': 2.6266647663933287e-06, 'batch_size': 4, 'num_train_epochs': 8, 'weight_decay': 0.012431516359530572}. Best is trial 10 with value: 0.8101404654877471.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning:

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-1000
Configuration saved in ./results/checkpoint-1000/config.json
Model weights saved in ./results/checkpoint-1000/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***

[I 2024-12-01 15:05:04,964] Trial 15 finished with value: 0.810442620782623 and parameters: {'learning_rate': 1.647740852390548e-05, 'batch_size': 4, 'num_train_epochs': 8, 'weight_decay': 0.0801887620431295}. Best is trial 15 with value: 0.810442620782623.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: This

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-1000
Configuration saved in ./results/checkpoint-1000/config.json
Model weights saved in ./results/checkpoint-1000/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***

[I 2024-12-01 15:09:04,079] Trial 16 finished with value: 0.8120991767217841 and parameters: {'learning_rate': 1.561386840216216e-05, 'batch_size': 4, 'num_train_epochs': 8, 'weight_decay': 0.09042209224942657}. Best is trial 16 with value: 0.8120991767217841.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: T

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-1000
Configuration saved in ./results/checkpoint-1000/config.json
Model weights saved in ./results/checkpoint-1000/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on huggingface.co/models =)


***

[I 2024-12-01 15:13:07,988] Trial 17 finished with value: 0.8122589802447074 and parameters: {'learning_rate': 1.7658878046243477e-05, 'batch_size': 4, 'num_train_epochs': 8, 'weight_decay': 0.08094396293465898}. Best is trial 17 with value: 0.8122589802447074.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: 

***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-500
Configuration saved in ./results/checkpoint-500/config.json
Model weights saved in ./results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./results/checkpoint-1000
Configuration saved in ./results/checkpoint-1000/config.json
Model weights saved in ./results/checkpoint-1000/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed

[I 2024-12-01 15:17:37,127] Trial 18 finished with value: 0.795601985136869 and parameters: {'learning_rate': 4.923215705386883e-05, 'batch_size': 4, 'num_train_epochs': 9, 'weight_decay': 0.03513439983890576}. Best is trial 17 with value: 0.8122589802447074.
<ipython-input-10-9265609bdcc0>:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform("learning_rate", 1e-6, 5e-5)
<ipython-input-10-9265609bdcc0>:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay = trial.suggest_loguniform("weight_decay", 1e-4, 0.1)
PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: Th

***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32
***** Running Evaluation *****
  Num examples = 260
  Batch size = 32


Training completed. Do not forget to share your model on huggingface.co/models =)


***** Running Evaluation *****
  Num examples = 260
  Batch size = 32


[I 2024-12-01 15:20:46,170] Trial 19 finished with value: 0.7940290034996405 and parameters: {'learning_rate': 1.5856472114281638e-05, 'batch_size': 16, 'num_train_epochs': 8, 'weight_decay': 0.007301952492841523}. Best is trial 17 with value: 0.8122589802447074.


Best trial:
FrozenTrial(number=17, state=TrialState.COMPLETE, values=[0.8122589802447074], datetime_start=datetime.datetime(2024, 12, 1, 15, 9, 4, 81983), datetime_complete=datetime.datetime(2024, 12, 1, 15, 13, 7, 988255), params={'learning_rate': 1.7658878046243477e-05, 'batch_size': 4, 'num_train_epochs': 8, 'weight_decay': 0.08094396293465898}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'learning_rate': FloatDistribution(high=5e-05, log=True, low=1e-06, step=None), 'batch_size': CategoricalDistribution(choices=(4, 8, 16)), 'num_train_epochs': IntDistribution(high=10, log=False, low=3, step=1), 'weight_decay': FloatDistribution(high=0.1, log=True, low=0.0001, step=None)}, trial_id=17, value=None)


In [12]:
best_hyperparams = study.best_trial.params

training_args = TrainingArguments(
    output_dir="./best_results",
    num_train_epochs=best_hyperparams["num_train_epochs"],
    per_device_train_batch_size=best_hyperparams["batch_size"],
    per_device_eval_batch_size=best_hyperparams["batch_size"] * 2,
    learning_rate=best_hyperparams["learning_rate"],
    weight_decay=best_hyperparams["weight_decay"],
    warmup_steps=10,
    evaluation_strategy="epoch",
    gradient_accumulation_steps=2,
    report_to="none",
)

trainer = OneHotTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics,
)
trainer.train()

PyTorch: setting up devices
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 1038
  Num Epochs = 8
  Instantaneous batch size per device = 4
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 2
  Total optimization steps = 1040


***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./best_results/checkpoint-500
Configuration saved in ./best_results/checkpoint-500/config.json
Model weights saved in ./best_results/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8
Saving model checkpoint to ./best_results/checkpoint-1000
Configuration saved in ./best_results/checkpoint-1000/config.json
Model weights saved in ./best_results/checkpoint-1000/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 260
  Batch size = 8


Training completed. Do not forget to share your model on 

TrainOutput(global_step=1040, training_loss=0.0006504525555870854, metrics={'train_runtime': 229.361, 'train_samples_per_second': 36.205, 'train_steps_per_second': 4.534, 'total_flos': 550053681979392.0, 'train_loss': 0.0006504525555870854, 'epoch': 8.0})

In [13]:
!mkdir 'best_model_distilbert_pharo'
!mkdir 'best_model_distilbert_pharo_tokenizer'

# Save model and tokenizer
trainer.save_model('./best_model_distilbert_pharo')
tokenizer.save_pretrained('./best_model_distilbert_pharo_tokenizer')

# Load model and tokenizer
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained('./best_model_distilbert_pharo')
tokenizer = DistilBertTokenizer.from_pretrained('./best_model_distilbert_pharo_tokenizer')

Saving model checkpoint to ./best_model_distilbert_pharo
Configuration saved in ./best_model_distilbert_pharo/config.json
Model weights saved in ./best_model_distilbert_pharo/pytorch_model.bin
tokenizer config file saved in ./best_model_distilbert_pharo_tokenizer/tokenizer_config.json
Special tokens file saved in ./best_model_distilbert_pharo_tokenizer/special_tokens_map.json
loading configuration file ./best_model_distilbert_pharo/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert-base-uncased",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "hidden_dim": 3072,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5",
    "6": "LABEL_6"
  },
  "initializer_range": 0.02,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "

## Model Testing

In [14]:
X_test = list(test_df['combo'])
y_test = list(test_df['labels'])

In [15]:
df_test = pd.DataFrame({"combo":X_test,"labels":y_test})
test_text = df_test.combo.values
test_label = df_test.labels.values

print(test_label)

[array([0, 0, 1, 1, 0, 0, 0]) array([0, 1, 0, 0, 0, 0, 0])
 array([0, 0, 1, 0, 0, 0, 0]) array([0, 0, 1, 0, 0, 0, 0])
 array([0, 0, 1, 0, 0, 0, 0]) array([0, 0, 1, 0, 0, 0, 0])
 array([0, 0, 1, 0, 0, 0, 0]) array([0, 0, 1, 0, 0, 0, 0])
 array([0, 1, 0, 0, 0, 0, 0]) array([0, 0, 0, 0, 1, 0, 0])
 array([0, 0, 0, 0, 1, 0, 0]) array([0, 0, 1, 0, 0, 0, 0])
 array([0, 0, 1, 0, 0, 0, 0]) array([0, 1, 0, 0, 0, 0, 0])
 array([0, 1, 0, 0, 0, 0, 0]) array([0, 1, 0, 0, 0, 0, 0])
 array([0, 1, 0, 0, 0, 0, 0]) array([0, 1, 0, 0, 0, 0, 0])
 array([0, 1, 0, 0, 0, 0, 0]) array([1, 0, 0, 0, 0, 0, 0])
 array([1, 0, 0, 0, 0, 0, 0]) array([1, 0, 0, 0, 0, 0, 0])
 array([1, 0, 0, 0, 0, 0, 0]) array([0, 0, 0, 0, 1, 0, 0])
 array([1, 0, 0, 0, 0, 0, 0]) array([0, 0, 0, 0, 0, 0, 1])
 array([0, 0, 0, 0, 0, 1, 0]) array([0, 0, 0, 0, 0, 1, 0])
 array([0, 0, 0, 0, 0, 1, 0]) array([1, 0, 0, 0, 0, 0, 0])
 array([0, 0, 0, 0, 1, 0, 0]) array([0, 0, 1, 0, 0, 0, 0])
 array([0, 0, 1, 0, 0, 0, 0]) array([0, 0, 1, 0, 0, 0, 0

In [16]:
type(test_label[0])

numpy.ndarray

In [17]:
test_dataset = TextClassificationDataset(test_text, test_label, tokenizer)

# Measure inference time
start_time = time.time()

# Predict on the test dataset
predictions = trainer.predict(test_dataset)

# Calculate elapsed time
end_time = time.time()
inference_time = end_time - start_time

# Compute metrics using the `compute_metrics` function
metrics = compute_metrics(predictions)

# Display metrics and inference time
print("Evaluation Metrics:", metrics)
print(f"Inference Time: {inference_time:.2f} seconds")

***** Running Prediction *****
  Num examples = 289
  Batch size = 8


Evaluation Metrics: {'accuracy': 0.9263470093919921, 'precision': 0.7581272892738996, 'recall': 0.7508305647840532, 'f1': 0.753951274874274}
Inference Time: 2.42 seconds


In [18]:
!zip -r best_model_distilbert_pharo.zip './best_model_distilbert_pharo'
!zip -r best_model_distilbert_pharo_tokenizer.zip './best_model_distilbert_pharo_tokenizer'

# For downloading model locally
# from google.colab import files
# files.download('checkpoint-6000.zip')

  adding: best_model_distilbert_pharo/ (stored 0%)
  adding: best_model_distilbert_pharo/pytorch_model.bin (deflated 8%)
  adding: best_model_distilbert_pharo/training_args.bin (deflated 51%)
  adding: best_model_distilbert_pharo/config.json (deflated 53%)
  adding: best_model_distilbert_pharo_tokenizer/ (stored 0%)
  adding: best_model_distilbert_pharo_tokenizer/tokenizer_config.json (deflated 43%)
  adding: best_model_distilbert_pharo_tokenizer/special_tokens_map.json (deflated 40%)
  adding: best_model_distilbert_pharo_tokenizer/vocab.txt (deflated 53%)


In [20]:
# prompt: transfer the checkpoint-6000.zip created to the google drive

from google.colab import drive
drive.mount('/content/drive')

!cp best_model_distilbert_pharo.zip "/content/drive/MyDrive/FYP/Revised/Models/DistilBert_pharo/"
!cp best_model_distilbert_pharo_tokenizer.zip "/content/drive/MyDrive/FYP/Revised/Models/DistilBert_pharo_Tokenizer/"

Mounted at /content/drive


In [ ]:
# Save the tokenizer
# tokenizer.save_pretrained('/content/drive/MyDrive/FYP/Revised/Models/DistilBert_Python_Tokenizer/')

# **Load and Test Model**

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [22]:
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification

# Replace 'path/to/checkpoint-folder' with the actual path to your checkpoint folder.
model_folder = '/content/drive/MyDrive/FYP/Revised/Models/DistilBert_pharo/'
tokenizer_folder = '/content/drive/MyDrive/FYP/Revised/Models/DistilBert_pharo_Tokenizer/'

!unzip '/content/drive/MyDrive/FYP/Revised/Models/DistilBert_pharo/best_model_distilbert_pharo.zip' -d './'
!unzip '/content/drive/MyDrive/FYP/Revised/Models/DistilBert_pharo_Tokenizer/best_model_distilbert_pharo_tokenizer.zip' -d './'

Archive:  /content/drive/MyDrive/FYP/Revised/Models/DistilBert_pharo/best_model_distilbert_pharo.zip
replace ./best_model_distilbert_pharo/pytorch_model.bin? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: ./best_model_distilbert_pharo/pytorch_model.bin  
  inflating: ./best_model_distilbert_pharo/training_args.bin  
  inflating: ./best_model_distilbert_pharo/config.json  
Archive:  /content/drive/MyDrive/FYP/Revised/Models/DistilBert_pharo_Tokenizer/best_model_distilbert_pharo_tokenizer.zip
replace ./best_model_distilbert_pharo_tokenizer/tokenizer_config.json? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: ./best_model_distilbert_pharo_tokenizer/tokenizer_config.json  
  inflating: ./best_model_distilbert_pharo_tokenizer/special_tokens_map.json  
  inflating: ./best_model_distilbert_pharo_tokenizer/vocab.txt  


In [23]:
best_model_distilbert_pharo = 'best_model_distilbert_pharo'
best_model_distilbert_pharo_tokenizer = 'best_model_distilbert_pharo_tokenizer'

In [27]:
# Load the model and tokenizer from the checkpoint
model = DistilBertForSequenceClassification.from_pretrained(best_model_distilbert_pharo)
tokenizer = DistilBertTokenizer.from_pretrained(best_model_distilbert_pharo_tokenizer)

text = "relative anchor takes an arbitrary element as"
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
output

loading configuration file best_model_distilbert_pharo/config.json
Model config DistilBertConfig {
  "_name_or_path": "distilbert-base-uncased",
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "hidden_dim": 3072,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    "4": "LABEL_4",
    "5": "LABEL_5",
    "6": "LABEL_6"
  },
  "initializer_range": 0.02,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2,
    "LABEL_3": 3,
    "LABEL_4": 4,
    "LABEL_5": 5,
    "LABEL_6": 6
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "pad_token_id": 0,
  "problem_type": "multi_label_classification",
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "torch_dtype": "float32",
  "transformers_version": "4.17.0",
  "voca

SequenceClassifierOutput(loss=None, logits=tensor([[ -7.6903, -11.9937,   8.0281, -14.3547, -13.3136, -12.5140, -10.8436]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [28]:
logits = output.logits

# Apply sigmoid to convert logits to probabilities
probabilities = torch.sigmoid(logits)

# Define a threshold to determine if a class is positive
threshold = 0.5
predicted_indices = (probabilities > threshold).nonzero(as_tuple=True)[1]

# Convert indices to a list for output
predicted_classes = (predicted_indices + 1).tolist()

# Format the output to display classes
if len(predicted_classes) > 0:
    predicted_classes_str = ", ".join(map(str, predicted_classes))
    print(f"Predicted class/es: {predicted_classes_str}")
else:
    print("No positive classes predicted.")

Predicted class/es: 3


In [26]:
# import torch

# # Logits from the model output
# logits =  output.logits #torch.tensor([[-17.5500, -13.8129, 9.7042, -16.6331, -6.6066]])

# # Get the index of the highest score
# predicted_class = ((torch.argmax(logits, dim=1).item()) + 1)

# print(f"Predicted class: {predicted_class}")
